<script setup lang="ts">
import type { Category } from '~/types/category'
import type { ProductFormData, VariationFormData } from '~/types/product'

definePageMeta({
  layout: 'default',
  title: 'Créer un produit',
  description: 'Ajouter un nouveau produit au catalogue'
})

// ========================================
// Types locaux
// ========================================
interface ImageData {
  id?: number
  url: string
  file?: File
  isNew: boolean
}

// ========================================
// Constantes
// ========================================
const MAX_IMAGES = 10

// ========================================
// Composables & Router
// ========================================
const router = useRouter()
const toast = useToast()

const { createProduct } = useProduct()
const { brands, fetchBrands } = useBrands()
const { categoryTree, fetchCategoryTree } = useCategories()

// ========================================
// État Local
// ========================================
const isSaving = ref(false)
const activeTab = ref('general')
const images = ref<ImageData[]>([])

// Form data avec valeurs par défaut
const form = ref<ProductFormData>({
  brand_id: undefined,
  categories: [],
  name: '',
  slug: '',
  sku: '',
  description: '',
  short_description: '',
  price: 0,
  compare_price: undefined,
  cost_price: undefined,
  status: 'draft',
  is_featured: false,
  is_new: true,
  is_on_sale: false,
  track_inventory: true,
  stock_quantity: 0,
  low_stock_threshold: 5,
  barcode: '',
  requires_authenticity: false,
  authenticity_codes_count: 0,
  is_preorder_enabled: false,
  preorder_available_date: undefined,
  preorder_limit: undefined,
  preorder_message: '',
  preorder_terms: '',
  meta_title: '',
  meta_description: '',
  is_variable: false,
  variations: [],
  images: [],
  images_to_delete: []
})

// ========================================
// Computed
// ========================================
const tabs = computed(() => [
  { key: 'general', label: 'Informations générales', slot: 'general' },
  { key: 'pricing', label: 'Prix & Stock', slot: 'pricing' },
  {
    key: 'media',
    label: 'Images',
    slot: 'media',
    badge: images.value.length || undefined
  },
  {
    key: 'variations',
    label: 'Variations',
    slot: 'variations',
    badge: form.value.variations.length || undefined,
    disabled: !form.value.is_variable
  },
  { key: 'seo', label: 'SEO', slot: 'seo' },
  { key: 'advanced', label: 'Avancé', slot: 'advanced' }
])

const statusOptions = [
  { label: 'Brouillon', value: 'draft', color: 'neutral' },
  { label: 'Actif', value: 'active', color: 'success' },
  { label: 'Inactif', value: 'inactive', color: 'error' },
  { label: 'Rupture', value: 'out_of_stock', color: 'warning' },
  { label: 'Précommande', value: 'preorder', color: 'info' },
  { label: 'Arrêté', value: 'discontinued', color: 'neutral' }
]

const brandOptions = computed(() => {
  return brands.value.map(brand => ({
    label: brand.name,
    value: brand.id,
    icon: brand.logo_url ? undefined : 'i-lucide-tag'
  }))
})

interface CategoryOption {
  label: string
  value: string
  level: number
}

const categoryOptions = computed(() => {
  const flattenCategories = (
    cats: readonly Category[],
    prefix = ''
  ): CategoryOption[] => {
    const result: CategoryOption[] = []

    for (const cat of cats) {
      result.push({
        label: prefix + cat.name,
        value: cat.id,
        level: cat.level
      })

      if (cat.children && cat.children.length > 0) {
        const childPrefix = prefix + '  '
        const childOptions = flattenCategories(cat.children, childPrefix)
        result.push(...childOptions)
      }
    }

    return result
  }

  return flattenCategories(categoryTree.value)
})

// ✅ SKU auto-généré
const autoGeneratedSku = computed(() => {
  if (!form.value.name) return ''

  const prefix = form.value.brand_id
    ? brands.value.find(b => b.id === form.value.brand_id)?.name.substring(0, 3).toUpperCase()
    : 'PRD'

  const timestamp = Date.now().toString().slice(-6)
  const namePart = form.value.name.substring(0, 3).toUpperCase().replace(/[^A-Z]/g, '')

  return `${prefix}-${namePart}-${timestamp}`
})

// Validation du formulaire
const formErrors = computed(() => {
  const errors: string[] = []

  if (!form.value.name?.trim()) {
    errors.push('Le nom du produit est requis')
  }

  if (form.value.price < 0) {
    errors.push('Le prix ne peut pas être négatif')
  }

  if (form.value.categories.length === 0) {
    errors.push('Au moins une catégorie est requise')
  }

  // ✅ Validation niveau catégories améliorée
  const invalidCategories = form.value.categories.filter(catId => {
    const cat = categoryOptions.value.find(c => c.value === catId)
    return cat && cat.level < 2
  })

  if (invalidCategories.length > 0) {
    const invalidNames = invalidCategories
      .map(id => categoryOptions.value.find(c => c.value === id)?.label)
      .filter(Boolean)
      .join(', ')

    errors.push(`Catégories invalides: ${invalidNames}. Sélectionnez des catégories de niveau 2+`)
  }

  if (form.value.compare_price && form.value.compare_price <= form.value.price) {
    errors.push('Le prix de comparaison doit être supérieur au prix de vente')
  }

  if (form.value.track_inventory && form.value.stock_quantity < 0) {
    errors.push('Le stock ne peut pas être négatif')
  }

  if (form.value.is_variable && form.value.variations.length === 0) {
    errors.push('Un produit variable doit avoir au moins une variation')
  }

  if (form.value.is_variable && form.value.variations.length > 0) {
    form.value.variations.forEach((v, idx) => {
      if (!v.variation_name?.trim()) {
        errors.push(`Variation ${idx + 1}: Le nom est requis`)
      }
      if (v.price < 0) {
        errors.push(`Variation ${idx + 1}: Le prix ne peut pas être négatif`)
      }
    })
  }

  return errors
})

const isFormValid = computed(() => {
  return form.value.name?.trim().length > 0 && form.value.categories.length > 0
})

// ========================================
// Methods - Gestion des Images
// ========================================

function handleImageUpload(files: File[]) {
  const availableSlots = MAX_IMAGES - images.value.length

  if (availableSlots <= 0) {
    toast.add({
      title: 'Limite atteinte',
      description: `Maximum de ${MAX_IMAGES} images atteint`,
      color: 'warning',
      icon: 'i-lucide-alert-triangle'
    })
    return
  }

  if (files.length > availableSlots) {
    toast.add({
      title: 'Trop d\'images',
      description: `Vous ne pouvez ajouter que ${availableSlots} image(s) supplémentaire(s)`,
      color: 'warning',
      icon: 'i-lucide-alert-triangle'
    })
    files = files.slice(0, availableSlots)
  }

  files.forEach(file => {
    if (file.size > 5 * 1024 * 1024) {
      toast.add({
        title: 'Fichier trop volumineux',
        description: `${file.name} dépasse 5MB`,
        color: 'error'
      })
      return
    }

    const url = URL.createObjectURL(file)
    images.value.push({
      url,
      file,
      isNew: true
    })
  })
}

function removeImage(index: number) {
  const img = images.value[index]

  if (img && img.isNew && img.url.startsWith('blob:')) {
    URL.revokeObjectURL(img.url)
  }

  images.value.splice(index, 1)
}

function reorderImages(oldIndex: number, newIndex: number) {
  const item = images.value[oldIndex]
  if (!item) return
  images.value.splice(oldIndex, 1)
  images.value.splice(newIndex, 0, item)
}

// ========================================
// Methods - Gestion des Variations
// ========================================

function addVariation() {
  form.value.variations.push({
    variation_name: '',
    price: form.value.price,
    compare_price: form.value.compare_price,
    cost_price: form.value.cost_price,
    stock_quantity: 0,
    stock_status: 'out_of_stock',
    is_active: true,
    attributes: {}
  })
}

function removeVariation(index: number) {
  form.value.variations.splice(index, 1)
}

function duplicateVariation(index: number) {
  const original = form.value.variations[index]
  if (!original) return

  form.value.variations.push({
    variation_name: `${original.variation_name} (copie)`,
    price: original.price,
    compare_price: original.compare_price,
    cost_price: original.cost_price,
    stock_quantity: original.stock_quantity,
    stock_status: original.stock_status,
    barcode: undefined,
    is_active: original.is_active,
    attributes: { ...original.attributes }
  })
}

// ========================================
// Methods - Sauvegarde
// ========================================

async function handleSave() {
  if (!isFormValid.value) {
    toast.add({
      title: 'Erreur de validation',
      description: formErrors.value[0] || 'Veuillez corriger les erreurs',
      color: 'error',
      icon: 'i-lucide-alert-circle'
    })
    return
  }

  isSaving.value = true

  try {
    const imageFiles = images.value
      .filter(img => img.file)
      .map(img => img.file!)

    const dataToSend: Record<string, any> = {
      name: form.value.name,
      slug: form.value.slug,
      sku: form.value.sku || autoGeneratedSku.value,
      price: form.value.price,
      status: form.value.status,
    }

    if (form.value.brand_id) {
      dataToSend.brand_id = form.value.brand_id
    }

    if (form.value.categories && form.value.categories.length > 0) {
      dataToSend.categories = form.value.categories
    }

    if (form.value.description) {
      dataToSend.description = form.value.description
    }
    if (form.value.short_description) {
      dataToSend.short_description = form.value.short_description
    }

    if (form.value.compare_price && form.value.compare_price > 0) {
      dataToSend.compare_price = form.value.compare_price
    }
    if (form.value.cost_price && form.value.cost_price > 0) {
      dataToSend.cost_price = form.value.cost_price
    }

    dataToSend.is_featured = form.value.is_featured ? 1 : 0
    dataToSend.is_new = form.value.is_new ? 1 : 0
    dataToSend.is_on_sale = form.value.is_on_sale ? 1 : 0
    dataToSend.is_variable = form.value.is_variable ? 1 : 0
    dataToSend.track_inventory = form.value.track_inventory ? 1 : 0
    dataToSend.requires_authenticity = form.value.requires_authenticity ? 1 : 0
    dataToSend.is_preorder_enabled = form.value.is_preorder_enabled ? 1 : 0

    dataToSend.stock_quantity = form.value.stock_quantity || 0
    dataToSend.low_stock_threshold = form.value.low_stock_threshold || 5

    if (form.value.requires_authenticity && form.value.authenticity_codes_count && form.value.authenticity_codes_count > 0) {
      dataToSend.authenticity_codes_count = form.value.authenticity_codes_count
    }

    if (form.value.is_preorder_enabled) {
      if (form.value.preorder_available_date) {
        dataToSend.preorder_available_date = form.value.preorder_available_date
      }
      if (form.value.preorder_limit && form.value.preorder_limit > 0) {
        dataToSend.preorder_limit = form.value.preorder_limit
      }
      if (form.value.preorder_message) {
        dataToSend.preorder_message = form.value.preorder_message
      }
      if (form.value.preorder_terms) {
        dataToSend.preorder_terms = form.value.preorder_terms
      }
    }

    if (form.value.meta_title) {
      dataToSend.meta_title = form.value.meta_title
    }
    if (form.value.meta_description) {
      dataToSend.meta_description = form.value.meta_description
    }

    if (form.value.is_variable && form.value.variations.length > 0) {
      dataToSend.variations = form.value.variations
    }

    if (imageFiles.length > 0) {
      dataToSend.images = imageFiles
    }

    console.log('📤 Données envoyées:', dataToSend)

    const created = await createProduct(dataToSend as ProductFormData)

    if (created) {
      toast.add({
        title: 'Produit créé',
        description: 'Le produit a été créé avec succès',
        color: 'success',
        icon: 'i-lucide-check-circle'
      })

      setTimeout(() => {
        router.push(`/products/${created.id}`)
      }, 500)
    } else {
      throw new Error('Échec de la création')
    }
  } catch (error: any) {
    console.error('❌ Create error:', error)

    const validationErrors = error.response?._data?.errors

    if (validationErrors && typeof validationErrors === 'object') {
      const errorList = Object.entries(validationErrors)
        .map(([field, messages]) => {
          const msgs = Array.isArray(messages) ? messages : [messages]
          return `• ${field}: ${msgs.join(', ')}`
        })
        .join('\n')

      toast.add({
        title: 'Erreur de validation',
        description: errorList,
        color: 'error',
        icon: 'i-lucide-alert-circle',
        duration: 7000
      })
    } else {
      toast.add({
        title: 'Erreur de création',
        description: error.response?._data?.message || error.message || 'Impossible de créer le produit',
        color: 'error',
        icon: 'i-lucide-x-circle'
      })
    }
  } finally {
    isSaving.value = false
  }
}

// ========================================
// Methods - Utilitaires
// ========================================

function generateSlug() {
  if (!form.value.name) return

  form.value.slug = form.value.name
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
}

function updateStockStatus(variation: VariationFormData) {
  variation.stock_status = variation.stock_quantity > 0 ? 'in_stock' : 'out_of_stock'
}

// ========================================
// Watchers
// ========================================

// ✅ Auto-générer SKU
watch(() => form.value.name, (newName) => {
  if (newName && !form.value.sku) {
    form.value.sku = autoGeneratedSku.value
  }
})

// ✅ Watcher optimisé pour variations
watch(() => form.value.variations.map(v => v.stock_quantity), (quantities) => {
  form.value.variations.forEach((v, idx) => {
    if (quantities[idx] !== undefined) {
      updateStockStatus(v)
    }
  })
}, { deep: false })

// ========================================
// Lifecycle
// ========================================

// Dans pages/products/create.vue
onMounted(async () => {
  console.log('🔍 Starting data fetch...')

  try {
    console.log('📦 Fetching brands...')
    await fetchBrands()
    console.log('✅ Brands loaded:', brands.value.length)
  } catch (error) {
    console.error('❌ Error loading brands:', error)
  }

  try {
    console.log('📂 Fetching category tree...')
    await fetchCategoryTree()
    console.log('✅ Category tree loaded:', categoryTree.value.length, 'root categories')
    console.log('📋 First category:', categoryTree.value[0])
  } catch (error) {
    console.error('❌ Error loading category tree:', error)
  }
})

onBeforeUnmount(() => {
  images.value.forEach(img => {
    if (img.isNew && img.url.startsWith('blob:')) {
      URL.revokeObjectURL(img.url)
    }
  })
})
</script>

<template>
  <UDashboardPanel>
    <!-- Header -->
    <template #header>
      <UDashboardNavbar>
        <template #left>
          <UButton icon="i-lucide-arrow-left" color="neutral" variant="ghost" to="/products" />
          <div class="ml-4">
            <h1 class="text-xl font-semibold text-gray-900 dark:text-white">
              Créer un produit
            </h1>
            <p class="text-sm text-gray-500">
              Ajouter un nouveau produit au catalogue
            </p>
          </div>
        </template>

        <template #right>
          <div class="flex items-center gap-2">
            <UButton label="Annuler" color="neutral" variant="ghost" to="/products" />
            <UButton
              label="Créer le produit"
              icon="i-lucide-plus"
              color="primary"
              :loading="isSaving"
              :disabled="!isFormValid"
              @click="handleSave"
            />
          </div>
        </template>
      </UDashboardNavbar>
    </template>

    <!-- Body -->
    <template #body>
      <div class="flex flex-col lg:flex-row gap-6">
        <!-- Sidebar gauche -->
        <div class="lg:w-[30%] space-y-6">
          <!-- Aperçu -->
          <UCard>
            <template #header>
              <h3 class="text-sm font-semibold">Aperçu</h3>
            </template>

            <div class="space-y-4">
              <!-- Image principale -->
              <div class="aspect-square rounded-lg overflow-hidden bg-gray-100 dark:bg-gray-800">
                <img
                  v-if="images[0]?.url"
                  :src="images[0].url"
                  alt="Aperçu"
                  class="w-full h-full object-cover"
                >
                <div v-else class="w-full h-full flex items-center justify-center">
                  <UIcon name="i-lucide-image" class="w-12 h-12 text-gray-400" />
                </div>
              </div>

              <!-- Statut -->
              <div>
                <label class="text-xs text-gray-500 mb-1 block">Statut</label>
                <USelectMenu
                  v-model="form.status"
                  :items="statusOptions"
                  value-key="value"
                  label-key="label"
                  placeholder="Sélectionner"
                  class="w-full"
                />
              </div>

              <!-- Stock initial -->
              <div v-if="form.track_inventory">
                <label class="text-xs text-gray-500 mb-1 block">Stock initial</label>
                <UInput
                  v-model.number="form.stock_quantity"
                  type="number"
                  placeholder="0"
                  class="w-full"
                />
              </div>

              <!-- Actions rapides -->
              <div class="pt-3 border-t border-gray-200 dark:border-gray-800 space-y-2">
                <UCheckbox v-model="form.is_featured" label="Produit mis en avant" />
                <UCheckbox v-model="form.is_new" label="Nouveau produit" />
                <UCheckbox v-model="form.is_on_sale" label="En promotion" />
              </div>
            </div>
          </UCard>

          <!-- Info -->
          <UAlert
            icon="i-lucide-info"
            color="primary"
            variant="soft"
            title="Conseil"
            description="Remplissez au minimum le nom et le prix pour créer le produit. Vous pourrez compléter les autres informations plus tard."
          />
        </div>

        <!-- Contenu principal -->
        <div class="flex-1">
          <UTabs v-model="activeTab" :items="tabs" class="w-full">
            <!-- Onglet: Général -->
            <template #general>
              <div class="space-y-6 p-6">
                <!-- Brand & Categories -->
                <div class="grid grid-cols-2 gap-4">
                  <UFormField label="Marque" required>
                    <USelectMenu
                      v-model="form.brand_id"
                      :items="brandOptions"
                      value-key="value"
                      label-key="label"
                      placeholder="Sélectionner une marque"
                      searchable
                      class="w-full"
                    >
                      <template #leading v-if="form.brand_id">
                        <UIcon name="i-lucide-tag" class="w-4 h-4 text-gray-400" />
                      </template>
                    </USelectMenu>
                  </UFormField>

                  <UFormField label="Catégories" required>
                    <USelectMenu
                      v-model="form.categories"
                      :items="categoryOptions"
                      value-key="value"
                      label-key="label"
                      placeholder="Sélectionner des catégories"
                      multiple
                      searchable
                      class="w-full"
                    >
                      <template #leading>
                        <UIcon name="i-lucide-folder-tree" class="w-4 h-4 text-gray-400" />
                      </template>

                      <template #item-label="{ item }">
                        <div class="flex items-center gap-2">
                          <span class="text-xs text-gray-400">Niv. {{ item.level }}</span>
                          <span>{{ item.label }}</span>
                        </div>
                      </template>
                    </USelectMenu>

                    <template #hint>
                      <span v-if="form.categories.length === 0" class="text-xs text-gray-400">
                        Sélectionnez au moins une catégorie
                      </span>
                      <span v-else class="text-xs text-gray-500">
                        {{ form.categories.length }} catégorie{{ form.categories.length > 1 ? 's' : '' }} sélectionnée{{ form.categories.length > 1 ? 's' : '' }}
                      </span>
                    </template>
                  </UFormField>
                </div>

                <!-- Badges des catégories sélectionnées -->
                <div v-if="form.categories.length > 0" class="flex flex-wrap gap-2">
                  <UBadge
                    v-for="catId in form.categories"
                    :key="catId"
                    color="primary"
                    variant="soft"
                    size="sm"
                    class="flex items-center gap-1"
                  >
                    <span>{{ categoryOptions.find(c => c.value === catId)?.label }}</span>
                    <UButton
                      icon="i-lucide-x"
                      color="primary"
                      variant="link"
                      size="xs"
                      :padded="false"
                      @click="form.categories = form.categories.filter(id => id !== catId)"
                    />
                  </UBadge>
                </div>

                <!-- Nom & Slug -->
                <div class="grid grid-cols-3 gap-4">
                  <UFormField label="Nom du produit" required class="col-span-2">
                    <UInput
                      v-model="form.name"
                      placeholder="Ex: T-shirt Nike Dri-FIT"
                      @blur="generateSlug"
                      class="w-full"
                    />
                  </UFormField>
                  <UFormField label="Slug" hint="Auto-généré">
                    <UInput
                      v-model="form.slug"
                      placeholder="t-shirt-nike-dri-fit"
                      disabled
                      class="w-full"
                    />
                  </UFormField>
                </div>

                <!-- SKU -->
                <UFormField label="SKU" hint="Auto-généré si vide">
                  <UInput
                    v-model="form.sku"
                    :placeholder="autoGeneratedSku"
                    class="w-1/2"
                  />
                </UFormField>

                <!-- Descriptions -->
                <UFormField label="Description courte">
                  <UTextarea
                    v-model="form.short_description"
                    :rows="3"
                    placeholder="Résumé en quelques mots..."
                    class="w-full"
                  />
                </UFormField>

                <UFormField label="Description complète">
                  <UTextarea
                    v-model="form.description"
                    :rows="8"
                    placeholder="Description détaillée du produit..."
                    class="w-full"
                  />
                </UFormField>
              </div>
            </template>

            <!-- Onglet: Prix & Stock -->
            <template #pricing>
              <div class="space-y-6 p-6">
                <div class="grid grid-cols-3 gap-4">
                  <UFormField label="Prix de vente" required>
                    <UInput
                      v-model.number="form.price"
                      type="number"
                      step="500"
                      placeholder="0"
                      class="w-full"
                    >
                      <template #trailing>
                        <span class="text-gray-400">CFA</span>
                      </template>
                    </UInput>
                  </UFormField>
                  <UFormField label="Prix comparaison">
                    <UInput
                      v-model.number="form.compare_price"
                      type="number"
                      step="500"
                      placeholder="0"
                      class="w-full"
                    >
                      <template #trailing>
                        <span class="text-gray-400">CFA</span>
                      </template>
                    </UInput>
                  </UFormField>
                  <UFormField label="Prix coûtant">
                    <UInput
                      v-model.number="form.cost_price"
                      type="number"
                      step="500"
                      placeholder="0"
                      class="w-full"
                    >
                      <template #trailing>
                        <span class="text-gray-400">CFA</span>
                      </template>
                    </UInput>
                  </UFormField>
                </div>

                <USeparator />

                <div class="space-y-4">
                  <UCheckbox v-model="form.track_inventory" label="Gérer le stock" />
                  <div v-if="form.track_inventory" class="grid grid-cols-2 gap-4 pl-6">
                    <UFormField label="Quantité en stock">
                      <UInput
                        v-model.number="form.stock_quantity"
                        type="number"
                        class="w-full"
                      />
                    </UFormField>
                    <UFormField label="Seuil stock faible">
                      <UInput
                        v-model.number="form.low_stock_threshold"
                        type="number"
                        class="w-full"
                      />
                    </UFormField>
                  </div>
                </div>
              </div>
            </template>

            <!-- Onglet: Images -->
            <template #media>
              <div class="p-6 space-y-6">
                <!-- Upload zone -->
                <div>
                  <label class="block text-sm font-medium mb-2">
                    Ajouter des images ({{ images.length }}/{{ MAX_IMAGES }})
                  </label>
                  <input
                    type="file"
                    multiple
                    accept="image/png,image/jpeg,image/webp"
                    @change="(e) => {
                      const files = (e.target as HTMLInputElement).files
                      if (files) handleImageUpload(Array.from(files))
                    }"
                    class="block w-full text-sm text-gray-500 file:mr-4 file:py-2 file:px-4 file:rounded-md file:border-0 file:text-sm file:font-semibold file:bg-primary-50 file:text-primary-700 hover:file:bg-primary-100"
                  />
                  <p class="mt-1 text-xs text-gray-500">PNG, JPG, WEBP jusqu'à 5MB par fichier</p>
                </div>

                <!-- Galerie d'images -->
                <div v-if="images.length > 0">
                  <div class="flex items-center justify-between mb-3">
                    <label class="block text-sm font-medium">Images du produit ({{ images.length }})</label>
                    <p class="text-xs text-gray-500">La première image sera l'image principale</p>
                  </div>

                  <div class="grid grid-cols-3 gap-4">
                    <div
                      v-for="(image, idx) in images"
                      :key="idx"
                      class="relative aspect-square rounded-lg overflow-hidden bg-gray-100 dark:bg-gray-800 group"
                    >
                      <img
                        :src="image.url"
                        :alt="`Image ${idx + 1}`"
                        class="w-full h-full object-cover"
                      />

                      <!-- Badge "Principal" -->
                      <div v-if="idx === 0" class="absolute top-2 left-2">
                        <UBadge color="primary" variant="solid" size="xs">Principal</UBadge>
                      </div>

                      <!-- Actions overlay -->
                      <div class="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-2">
                        <UButton
                          v-if="idx > 0"
                          icon="i-lucide-arrow-left"
                          color="neutral"
                          variant="solid"
                          size="xs"
                          @click="reorderImages(idx, idx - 1)"
                        />
                        <UButton
                          icon="i-lucide-trash-2"
                          color="error"
                          variant="solid"
                          size="xs"
                          @click="removeImage(idx)"
                        />
                        <UButton
                          v-if="idx < images.length - 1"
                          icon="i-lucide-arrow-right"
                          color="neutral"
                          variant="solid"
                          size="xs"
                          @click="reorderImages(idx, idx + 1)"
                        />
                      </div>
                    </div>
                  </div>
                </div>

                <!-- Message si aucune image -->
                <UAlert
                  v-else
                  icon="i-lucide-image"
                  color="neutral"
                  variant="soft"
                  title="Aucune image"
                  description="Ajoutez des images pour mettre en valeur votre produit"
                />
              </div>
            </template>

            <!-- Onglet: Variations -->
            <template #variations>
              <div class="space-y-6 p-6">
                <!-- Message si produit non variable -->
                <UAlert
                  v-if="!form.is_variable"
                  icon="i-lucide-info"
                  color="secondary"
                  variant="soft"
                  title="Produit simple"
                  description="Activez 'Produit avec variations' dans l'onglet Avancé pour gérer les variations."
                />

                <!-- Gestion des variations -->
                <div v-else class="space-y-4">
                  <!-- Header -->
                  <div class="flex items-center justify-between">
                    <div>
                      <h3 class="text-lg font-semibold">Variations du produit</h3>
                      <p class="text-sm text-gray-500">{{ form.variations.length }} variation(s)</p>
                    </div>
                    <UButton
                      icon="i-lucide-plus"
                      label="Ajouter une variation"
                      color="primary"
                      @click="addVariation"
                    />
                  </div>

                  <!-- Liste des variations -->
                  <div v-if="form.variations.length > 0" class="space-y-3">
                    <UCard v-for="(variation, idx) in form.variations" :key="idx">
                      <div class="space-y-4">
                        <!-- Header de la variation -->
                        <div class="flex items-start justify-between gap-4">
                          <UFormField label="Nom de la variation" class="flex-1">
                            <UInput
                              v-model="variation.variation_name"
                              placeholder="Ex: Rouge / Taille L"
                              class="w-full"
                            />
                          </UFormField>

                          <div class="flex gap-1 mt-6">
                            <UButton
                              icon="i-lucide-copy"
                              color="neutral"
                              variant="ghost"
                              size="sm"
                              @click="duplicateVariation(idx)"
                            />
                            <UButton
                              icon="i-lucide-trash-2"
                              color="error"
                              variant="ghost"
                              size="sm"
                              @click="removeVariation(idx)"
                            />
                          </div>
                        </div>

                        <!-- Prix et Stock -->
                        <div class="grid grid-cols-3 gap-4">
                          <UFormField label="Prix">
                            <UInput
                              v-model.number="variation.price"
                              type="number"
                              step="500"
                              class="w-full"
                            >
                              <template #trailing>
                                <span class="text-gray-400">CFA</span>
                              </template>
                            </UInput>
                          </UFormField>

                          <UFormField label="Prix comparaison">
                            <UInput
                              v-model.number="variation.compare_price"
                              type="number"
                              step="500"
                              class="w-full"
                            >
                              <template #trailing>
                                <span class="text-gray-400">CFA</span>
                              </template>
                            </UInput>
                          </UFormField>

                          <UFormField label="Stock">
                            <UInput
                              v-model.number="variation.stock_quantity"
                              type="number"
                              class="w-full"
                            />
                          </UFormField>
                        </div>

                        <!-- SKU -->
                        <UFormField label="SKU (optionnel)">
                          <UInput
                            v-model="variation.sku"
                            placeholder="Généré automatiquement si vide"
                            class="w-1/2"
                          />
                        </UFormField>

                        <!-- Statut actif -->
                        <UCheckbox v-model="variation.is_active" label="Variation active" />
                      </div>
                    </UCard>
                  </div>

                  <!-- Message si aucune variation -->
                  <UAlert
                    v-else
                    icon="i-lucide-package"
                    color="neutral"
                    variant="soft"
                    title="Aucune variation"
                    description="Cliquez sur 'Ajouter une variation' pour proposer différentes options de ce produit."
                  />
                </div>
              </div>
            </template>

            <!-- Onglet: SEO -->
            <template #seo>
              <div class="space-y-6 p-6">
                <UFormField label="Titre SEO">
                  <UInput
                    v-model="form.meta_title"
                    placeholder="Titre pour les moteurs de recherche"
                    class="w-full"
                  />
                  <template #hint>
                    <span class="text-xs">{{ form.meta_title?.length || 0 }}/60 caractères recommandés</span>
                  </template>
                </UFormField>

                <UFormField label="Description SEO">
                  <UTextarea
                    v-model="form.meta_description"
                    :rows="6"
                    placeholder="Description pour les moteurs de recherche"
                    class="w-full"
                  />
                  <template #hint>
                    <span class="text-xs">{{ form.meta_description?.length || 0 }}/160 caractères recommandés</span>
                  </template>
                </UFormField>

                <!-- Aperçu Google -->
                <div class="p-4 border border-gray-200 dark:border-gray-800 rounded-lg">
                  <p class="text-xs text-gray-500 mb-2">Aperçu Google</p>
                  <div class="space-y-1">
                    <h4 class="text-blue-600 text-lg">{{ form.meta_title || form.name || 'Nouveau produit' }}</h4>
                    <p class="text-xs text-green-700">{{ `https://votresite.com/products/${form.slug || 'nouveau-produit'}` }}</p>
                    <p class="text-sm text-gray-600">
                      {{ form.meta_description || form.short_description || 'Aucune description' }}
                    </p>
                  </div>
                </div>
              </div>
            </template>

            <!-- Onglet: Avancé -->
            <template #advanced>
              <div class="space-y-6 p-6">
                <UFormField label="Configuration avancée">
                  <div class="space-y-3">
                    <UCheckbox
                      v-model="form.requires_authenticity"
                      label="Requiert authentification Bylin"
                    >
                      <template #description>
                        Les clients devront vérifier l'authenticité du produit
                      </template>
                    </UCheckbox>

                    <UCheckbox
                      v-model="form.is_variable"
                      label="Produit avec variations"
                    >
                      <template #description>
                        Ce produit a différentes options (taille, couleur, etc.)
                      </template>
                    </UCheckbox>

                    <UCheckbox
                      v-model="form.is_preorder_enabled"
                      label="Activer la précommande"
                    >
                      <template #description>
                        Permettre aux clients de précommander ce produit
                      </template>
                    </UCheckbox>
                  </div>
                </UFormField>

                <!-- Options de précommande -->
                <div
                  v-if="form.is_preorder_enabled"
                  class="pl-6 space-y-4 border-l-2 border-primary-200 dark:border-primary-800"
                >
                  <UFormField label="Date de disponibilité">
                    <UInput
                      v-model="form.preorder_available_date"
                      type="date"
                      class="w-1/2"
                    />
                  </UFormField>

                  <UFormField label="Limite de précommandes">
                    <UInput
                      v-model.number="form.preorder_limit"
                      type="number"
                      placeholder="Illimité"
                      class="w-1/2"
                    />
                  </UFormField>

                  <UFormField label="Message de précommande">
                    <UTextarea
                      v-model="form.preorder_message"
                      :rows="3"
                      placeholder="Ex: Disponible le 15 janvier"
                      class="w-full"
                    />
                  </UFormField>
                </div>

                <!-- Erreurs de validation -->
                <UAlert
                  v-if="formErrors.length > 0"
                  icon="i-lucide-alert-circle"
                  color="error"
                  variant="soft"
                  title="Erreurs de validation"
                >
                  <ul class="list-disc list-inside space-y-1 text-sm">
                    <li v-for="(error, idx) in formErrors" :key="idx">{{ error }}</li>
                  </ul>
                </UAlert>

                <!-- Info validation -->
                <UAlert
                  v-else
                  icon="i-lucide-check-circle"
                  color="success"
                  variant="soft"
                  title="Formulaire valide"
                  description="Tous les champs requis sont remplis. Vous pouvez créer le produit."
                />
              </div>
            </template>
          </UTabs>
        </div>
      </div>
    </template>
  </UDashboardPanel>
</template>
